### ISSUE TITLE
Antispam not working after install

### ISSUE THREAD

**Issue by raphraph** [schulle4u/yellow-extensions-schulle4u#37]
Hi, I used to have antispam extension installed and working on my yellow website.

I had to reinstall totally my system and since I can't manage to make antispam work anymore...

This is the `php yellow.php about` output :
```
Datenstrom Yellow 0.9
Core 0.9.9
Edit 0.9.6
English 0.9.1
French 0.9.1
Gallery 0.9.2
Generate 0.9.5
German 0.9.1
Image 0.9.3
Markdown 0.9.1
Serve 0.9.1
Slider 0.9.2
Stockholm 0.9.2
Update 0.9.4
```
Antispam is not listed, I don't know if it's normal.
However Antispam is correctly listed in the `yellow-extension.ini` file.

The `antispam.js` and `antispam.php` files are correctly created after copying the .zip file into the extensions folder.

When reinstalling the system (yellow is running as a yunohost app on my server) I had to do a manual backup/recover, and I'm wondering if something somewhere has been wrongly backed up/restored by myself.

I think there was a yellow update when I reinstalled it, so I was wondering if the app could be broken or not.

Thanks for your help, and thanks for this extension that worked fine on my previous install.

**Comment by schulle4u** [comment]
Thanks for letting me know that this extension is still in use somewhere. Sorry for being a little slow updating my code for the latest API changes. 🙂 

The antispam extension has been updated. Due to Yellows publishing requirements, the extensions in this repository  are considered experimental and cannot be automatically updated. Please [manually download antispam.zip](https://github.com/schulle4u/yellow-extensions-schulle4u/raw/main/downloads/antispam.zip) and copy it into your `system/extensions` folder.

**Comment by raphraph** [comment]
Wow thanks for your reactivity ! :)

Yes I noticed the "experimental", no problem. I downloaded it and it's working fine now :+1: 

I was surprised to be able to read clearly the email when inspecting the page in firefox, but looking at the page source code I see that the email is not written "in clear" (sorry this is french, I don't know how to translate it) so suppose it's working fine.

Thanks again :)
